[workspace]
authors = ["Jia Liu <proljc@gmail.com>"]
channels = ["https://conda.modular.com/max", "conda-forge"]
name = "tokl"
platforms = ["osx-arm64", "linux-64"]
version = "0.1.3"

[tasks]
build = "sh scripts/gen_version.sh && mojo build src/main.mojo -o tokl"

[dependencies]
mojo = ">=1.0.0,<2"
max = ">=26.5.0,<27"
